### ISSUE TITLE
external component not detected

### ISSUE THREAD

**Issue by clowrey** [nielsnl68/SwitchPlate#8]
I am trying to test this out but it seems the external component is not being pulled in or maybe something changed in the component itself since the documentation was updated? I have used other external components so think that is setup right, its mostly a copy from your readme but I am going to use the WT-SC01 LCD so didn't need the resistive touch driver, problem occurs either way. 

Here is the error:

```
INFO Reading configuration /config/esphome/esp32-wt-sc01-switchplate.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/3796/head
INFO Updating https://github.com/nielsnl68/SwitchPlate.git@main
INFO Updating https://github.com/gpambrozio/esphome.git@FT6336U-touch
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Detected timezone 'Pacific/Honolulu'
WARNING GPIO15 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

switch.switchplate: [source /config/esphome/esp32-wt-sc01-switchplate.yaml:147]
  
  Platform not found: 'switch.switchplate'.
  platform: switchplate
  widget_id: my_sw_image
  name: ${device} my_sw_image
switchplate: [source /config/esphome/esp32-wt-sc01-switchplate.yaml:152]
  
  Component not found: switchplate.
  id: my_plate
  display_id: my_display
  touchscreen_id: my_toucher
  default_font: my_font
```

Here is the YAML:

```
esphome:
  name: esp32-wt-sc01-switchplate

# Adds the switchplate component to your instance of esphome 
external_components:
  # development of the updated components needed to use the SwitchPlate 
  - source: github://pr#3796
    components: [display, animation]
    refresh: 10s
  - source: github://nielsnl68/SwitchPlate@main
    components: [switchplate, ili9xxx]
    refresh: 10s
  - source: github://gpambrozio/esphome@FT6336U-touch
    components: [ ft63x6 ]
    refresh: 1min

    # to run everything you need to use a resent version of the arduino platform and ioplatform
esp32:
  board: m5stack-core2
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0

# Enable logging
logger:

# Enable Home Assistant API
api:

time:
  - platform: homeassistant
    id: the_time
    
color:
  - id: my_light_red
    red: 100%
  - id: my_black
    blue: 0%
    green: 0%
    red: 0%
  - id: my_red
    red: 100%
  - id: color_blue
    blue: 86%
  - id: my_white
    red: 100%
    blue: 100%
    green: 100%
  - id: my_blue
    red: 0%
    blue: 100%
    green: 0%
  - id: my_green
    red: 0%
    blue: 0%
    green: 100%
  - id: my_yellow
    red: 75%
    green: 75%
  - id: my_light_blue
    red_int: 96
    green_int: 96
    blue_int: 255

light:
  - platform: monochromatic
    name: "Display Backlight"
    output: lcd_backlight

# Example output entry
output:
  - platform: ledc
    id: lcd_backlight
    pin: 23

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13

i2c:
  sda: 18
  scl: 19
  scan: false

font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 20

display:
  - id: my_display
    platform: ili9xxx
    model: ST7796
    cs_pin: GPIO15
    dc_pin: GPIO21
    reset_pin: GPIO22
    auto_clear_enabled: false

touchscreen:
  - platform: ft63x6
    display: my_display
    id: my_toucher
    on_touch:
      - logger.log:
          format: Touch at (%d, %d)
          args: [touch.x, touch.y]

image:
  - file: "images/logo.png"
    id: my_image
    resize: 100x100
    type: TRANSPARENT_BINARY

animation:
  - file: "images/writingpen.gif"
    id: my_animation
    resize: 100x100
    type: TRANSPARENT_BINARY

interval:
  - interval: 200ms
    then:
      lambda: |-
        id(my_animation).next_frame();
        id(my_display).call_update();

switch:
  - platform: switchplate
    widget_id: my_sw_image
    name: ${device} my_sw_image

switchplate:
  id: my_plate
  display_id: my_display # Req
  touchscreen_id: my_toucher
  default_font: my_font
  header:
    - type: pagetitle
      dimension:
        x: 2
        y: 0
        width: 198
        height: 20
    - type: datetime
      id: theTime
      time_id: the_time
      dimension:
        x: 240
        y: 0
        width: 120
        height: 20

  pages:
    - id: myButtons
      title: Woonkamer lampen
      selectable: true # can be opened with next and previous page selectors
      widgets:
        - type: image
          id: rgbLamp
          image_id: my_image0
          image_color: my_light_blue
          dimension:
            x: 5
            y: 30
            width: 96
            height: 96

    - id: myMainPage # Opt.
      title: Basic widgets
      selectable: true # can be opened with next and previous page selectors
      widgets:
        - type: label
          id: txtHello
          dimension:
            x: 10
            y: 30
            width: 300
            height: 20
          content: "I am your SwitchPlate"
        - type: button
          id: btnClick
          dimension:
            x: 60
            y: 180
            width: 200
            height: 40
          border_color: my_yellow
          content: "Click me"
          action: home

        - type: image
          id: my_sw_image
          image_id: my_image
          image_color: my_green
          border_radius: 8
          pressed:
            image_color: my_blue
            border_color: my_blue
          selected:
            image_color: my_yellow
            border_color: my_yellow

          selectable: true
          clickable: true
          dimension:
            x: 10
            y: 70
            width: 100
            height: 100
        - type: image
          image_id: my_animation
          image_color: my_blue
          dimension:
            x: 170
            y: 70
            width: 100
            height: 100
```
